#!/usr/bin/env bash
folder="/home/potato/Desktop/PCI"
bochsFolder="/home/potato/Desktop/Bochs Folder"
src="$folder/src"
bin="$folder/bin"
cd "$folder"
nasm -f bin "$src/pci.asm" -l pci.lst -o "$bin/pci"
sudo dd if="$bin/pci" of="$bochsFolder/pci.iso" bs=512 count=1 | hexdump -C
sudo chmod u=rwx,g=rwx,o=rwx "$bochsFolder/pci.iso"
cd "$bochsFolder"
bochs
$SHELL
